In [1]:
import pandas as pd
df = pd.read_csv('data.Mod1ProjData.csv')
df.describe()

,Unnamed: 0,id_y,production_budget,year,domestic_gross,worldwide_gross,festival,D3,IMAX,title_y,...,self_age,producer_age,composer_age,archive_sound_age,cinematographer_age,actor_ordering,actress_ordering,actress_ratio,averagerating,numvotes
count,3859.000000,1813.000000,1.813000e+03,3859.000000,3.830000e+03,2.532000e+03,3859.000000,3859.000000,3859.000000,3859.000000,...,140.000000,1453.000000,990.000000,1.0,542.000000,3456.000000,3111.00000,3550.000000,3574.000000,3.574000e+03
mean,1929.000000,51.629344,4.569651e+07,2014.064784,3.008585e+07,1.162798e+08,0.097435,0.052863,0.006737,12.267686,...,1956.408929,1963.338759,1964.519697,1916.0,1962.556273,2.508997,2.61279,0.385379,6.415753,5.708332e+04
std,1114.141673,28.624432,5.368251e+07,2.454553,6.801094e+07,2.109386e+08,0.344310,0.274743,0.081816,9.522809,...,16.233772,10.500009,12.118448,NaN,12.017665,0.783560,1.00176,0.232976,1.040687,1.214320e+05
min,0.000000,1.000000,5.000000e+04,2010.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.000000,...,1925.000000,1924.000000,1796.000000,1916.0,1930.000000,1.000000,1.00000,0.000000,1.600000,5.000000e+00
25%,964.500000,27.000000,1.000000e+07,2012.000000,1.252500e+05,7.703443e+06,0.000000,0.000000,0.000000,4.000000,...,1944.500000,1956.000000,1957.000000,1916.0,1954.000000,2.000000,2.00000,0.250000,5.900000,1.498750e+03
50%,1929.000000,52.000000,2.600000e+07,2014.000000,1.803064e+06,3.871803e+07,0.000000,0.000000,0.000000,11.000000,...,1956.583333,1964.000000,1966.000000,1916.0,1962.000000,2.500000,2.50000,0.428571,6.500000,1.038550e+04
75%,2893.500000,76.000000,5.620000e+07,2016.000000,3.144501e+07,1.226372e+08,0.000000,0.000000,0.000000,20.000000,...,1967.000000,1971.000000,1972.000000,1916.0,1970.750000,2.666667,3.00000,0.500000,7.100000,5.530975e+04
max,3858.000000,100.000000,4.106000e+08,2018.000000,9.366622e+08,2.053311e+09,3.000000,5.000000,1.000000,48.000000,...,1997.000000,1990.000000,1992.000000,1916.0,1990.000000,8.000000,10.00000,1.000000,9.200000,1.841066e+06

In [5]:
df[df.domestic_gross>0].domestic_gross.sort_values().head(10)

2407    100.0
2905    300.0
2904    300.0
3828    300.0
3173    300.0
2114    400.0
3399    400.0
3398    500.0
2214    600.0
2406    700.0
Name: domestic_gross, dtype: float64

| Metrics | Production Budget | Domestic Gross | Foreign Gross | Worldwide Gross |
|---------|-------------------|----------------|---------------|-----------------|
| Average | 45696510          | 30085850       | 86193950      | 116279800       |
| Minimum | 50000             | 100            | 1142          | 1242            |
| 25%     | 10000000          | 125250         | 7578193       | 7703443         |
| 50%     | 26000000          | 1803064        | 36914966      | 38718030        |
| 75%     | 56200000          | 31445010       | 91192190      | 122637200       |
| Maximum | 410600000         | 936662200      | 1116648800    | 2053311000      |